// Generated by gencpp from file my_service/rouletteRequest.msg
// DO NOT EDIT!


#ifndef MY_SERVICE_MESSAGE_ROULETTEREQUEST_H
#define MY_SERVICE_MESSAGE_ROULETTEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace my_service
{
template <class ContainerAllocator>
struct rouletteRequest_
{
  typedef rouletteRequest_<ContainerAllocator> Type;

  rouletteRequest_()
    : number(0)
    , color()  {
    }
  rouletteRequest_(const ContainerAllocator& _alloc)
    : number(0)
    , color(_alloc)  {
  (void)_alloc;
    }



   typedef int32_t _number_type;
  _number_type number;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _color_type;
  _color_type color;





  typedef boost::shared_ptr< ::my_service::rouletteRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::my_service::rouletteRequest_<ContainerAllocator> const> ConstPtr;

}; // struct rouletteRequest_

typedef ::my_service::rouletteRequest_<std::allocator<void> > rouletteRequest;

typedef boost::shared_ptr< ::my_service::rouletteRequest > rouletteRequestPtr;
typedef boost::shared_ptr< ::my_service::rouletteRequest const> rouletteRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::my_service::rouletteRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::my_service::rouletteRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::my_service::rouletteRequest_<ContainerAllocator1> & lhs, const ::my_service::rouletteRequest_<ContainerAllocator2> & rhs)
{
  return lhs.number == rhs.number &&
    lhs.color == rhs.color;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::my_service::rouletteRequest_<ContainerAllocator1> & lhs, const ::my_service::rouletteRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace my_service

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::my_service::rouletteRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_service::rouletteRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_service::rouletteRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_service::rouletteRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_service::rouletteRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_service::rouletteRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::my_service::rouletteRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1435a5fb48160afe96f823952c132324";
  }

  static const char* value(const ::my_service::rouletteRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1435a5fb48160afeULL;
  static const uint64_t static_value2 = 0x96f823952c132324ULL;
};

template<class ContainerAllocator>
struct DataType< ::my_service::rouletteRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "my_service/rouletteRequest";
  }

  static const char* value(const ::my_service::rouletteRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::my_service::rouletteRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 number\n"
"string color\n"
;
  }

  static const char* value(const ::my_service::rouletteRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::my_service::rouletteRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.number);
      stream.next(m.color);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct rouletteRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::my_service::rouletteRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::my_service::rouletteRequest_<ContainerAllocator>& v)
  {
    s << indent << "number: ";
    Printer<int32_t>::stream(s, indent + "  ", v.number);
    s << indent << "color: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.color);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MY_SERVICE_MESSAGE_ROULETTEREQUEST_H
